language: php

php:
  - '5.6'

install: composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - mv build/logs/clover.xml build/logs/coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover